DROP DATABASE IF EXISTS MUZEU;
CREATE DATABASE IF NOT EXISTS MUZEU;
USE MUZEU;

CREATE TABLE IF NOT EXISTS INSTITUTIE
(
	ID INT NOT NULL AUTO_INCREMENT, 
    DENUMIRE VARCHAR(50) NOT NULL,
    ADRESA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TABLOU_MUZEU
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLU VARCHAR(50) NOT NULL,
    ARTIST VARCHAR(50) NOT NULL,
    AN_REALIZARE INT NOT NULL,
    GEN_PICTURA VARCHAR(50) NOT NULL,
    TEHNICA VARCHAR(50) NOT NULL,
    ID_INSTITUTIE INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_INSTITUTIE) REFERENCES INSTITUTIE (ID)
);

CREATE TABLE IF NOT EXISTS TABLOU_GALERIE
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLU VARCHAR(50) NOT NULL,
    ARTIST VARCHAR(50) NOT NULL,
    AN_REALIZARE INT NOT NULL,
    GEN_PICTURA VARCHAR(50) NOT NULL,
    PRET INT NOT NULL,
	TEHNICA VARCHAR(50) NOT NULL,
    ID_INSTITUTIE INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (ID_INSTITUTIE) REFERENCES INSTITUTIE (ID)
);

CREATE TABLE IF NOT EXISTS SCULPTURA_MUZEU
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLU VARCHAR(50) NOT NULL,
    ARTIST VARCHAR(50) NOT NULL,
    AN_REALIZARE INT NOT NULL,
    TIP_SCULPTURA VARCHAR(50) NOT NULL,
    ID_INSTITUTIE INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_INSTITUTIE) REFERENCES INSTITUTIE (ID)
);

CREATE TABLE IF NOT EXISTS SCULPTURA_GALERIE
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLU VARCHAR(50) NOT NULL,
    ARTIST VARCHAR(50) NOT NULL,
    AN_REALIZARE INT NOT NULL,
    TIP_SCULPTURA VARCHAR(50) NOT NULL,
    ID_INSTITUTIE INT NOT NULL,
    PRET INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_INSTITUTIE) REFERENCES INSTITUTIE (ID)
);

CREATE TABLE IF NOT EXISTS ADMINISTRATOR
(
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT NULL,
    PAROLA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ANGAJAT
(
	ID INT NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT NULL,
    PAROLA VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);
